/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useRef } from "react";
import * as THREE from "three";

// @ts-expect-error - props type unknown
export function Ruby(props) {
  const { nodes, materials } = useGLTF("/models/ruby.gltf");

  const rubyref = useRef<THREE.Mesh>(null);

  useFrame(() => {
    if (rubyref.current) {
      rubyref.current.rotation.y += 0.01;
    }
  });
  return (
    <group {...props} dispose={null}>
      <mesh
        ref={rubyref}
        castShadow
        receiveShadow
        // @ts-expect-error - TS doesn't like the geometry prop
        geometry={nodes.Ruby.geometry}
        material={materials.Material}
      />
    </group>
  );
}

useGLTF.preload("/models/ruby.gltf");
