/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";

// @ts-expect-error - props type unknown
export function Tree(props) {
  const { nodes, materials } = useGLTF("/models/tree.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        // @ts-expect-error - TS doesn't like the geometry prop
        geometry={nodes.Tree.geometry}
        material={materials["wood.005"]}
      >
        <mesh
          castShadow
          receiveShadow
          // @ts-expect-error - TS doesn't like the geometry prop
          geometry={nodes.Cube.geometry}
          material={materials["tree.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          // @ts-expect-error - TS doesn't like the geometry prop
          geometry={nodes.Cube002.geometry}
          material={materials["tree.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          // @ts-expect-error - TS doesn't like the geometry prop
          geometry={nodes.Cube003.geometry}
          material={materials["tree.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          // @ts-expect-error - TS doesn't like the geometry prop
          geometry={nodes.Cube004.geometry}
          material={materials["tree.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          // @ts-expect-error - TS doesn't like the geometry prop
          geometry={nodes.Cube005.geometry}
          material={materials["tree.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          // @ts-expect-error - TS doesn't like the geometry prop
          geometry={nodes.Cube006.geometry}
          material={materials["tree.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          // @ts-expect-error - TS doesn't like the geometry prop
          geometry={nodes.Cube007.geometry}
          material={materials["tree.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          // @ts-expect-error - TS doesn't like the geometry prop
          geometry={nodes.Cube008.geometry}
          material={materials["tree.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          // @ts-expect-error - TS doesn't like the geometry prop
          geometry={nodes.Cube009.geometry}
          material={materials["tree.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          // @ts-expect-error - TS doesn't like the geometry prop
          geometry={nodes.Cube010.geometry}
          material={materials["tree.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          // @ts-expect-error - TS doesn't like the geometry prop
          geometry={nodes.Cube011.geometry}
          material={materials["tree.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          // @ts-expect-error - TS doesn't like the geometry prop
          geometry={nodes.Cube012.geometry}
          material={materials["tree.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          // @ts-expect-error - TS doesn't like the geometry prop
          geometry={nodes.Cube025.geometry}
          material={materials.tree}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/tree.gltf");
